### ISSUE TITLE
RangeError: Error #1125 at starling.display::DisplayObjectContainer/render()

### ISSUE THREAD

**Issue by LvLynx** [Gamua/Starling-Framework#725]
Our users sometimes encounter a starling error, that we cant reproduce. Game is running starling 1.7 RC1

We logged some stats from game:
playerMemory: 130MB fullMemory: 429MB freeMemory: 32MB CPU: 0.00 averageFPS: 36.75 played: 2.65min 
flash version: WIN 17,0,0,188 

Compiled with ascsh v0.4 (flashDevelop, SDK: AIR 16.0.0)

stackTrace:RangeError: Error #1125 at starling.display::DisplayObjectContainer/render() at starling.display::Sprite/render() at starling.display::DisplayObjectContainer/render() at starling.display::Sprite/render() at starling.display::DisplayObjectContainer/render() at starling.display::Sprite/render() at starling.display::DisplayObjectContainer/render() at starling.core::Starling/render() at starling.core::Starling/nextFrame() at starling.core::Starling/onEnterFrame()

Is it something on our end? Or bug in library?

**Comment by PrimaryFeather** [comment]
Sorry for the late reply — I just return from a vacation and am still working through all that popped up in the meantime.

Hm ... that shouldn't happen (of course), but it's a little hard to get to the root of the problem without more information.

Are you using any plugins or other third-party code?
And do you override "render" anywhere in your code?

One reason I could think of that could cause such an error is if you change the number of children of a container while the same container is being rendered. 

Is there any place in your code where this could be happening?

**Comment by LvLynx** [comment]
Yes, we do use third party Starling extensions:
1) Feathers (not much though) http://feathersui.com/
2) Graphics a lot http://wiki.starling-framework.org/extensions/graphics
3) QuadtreeSprite extensively (it is used for our primary game map with lots of objects) http://wiki.starling-framework.org/extensions/quadtreesprite

But we do not override render ourselves anywhere yet.

There is a new version of Feathers and Graphics available. We will update them and see if errors still happen.

**Comment by PrimaryFeather** [comment]
Thanks for the additional information!
Since you do not override render yourself, and this is the first time I'm seeing such an error report, my guess is that it's an extension problem — but it might still be a Starling issue, of course.

Updating those libraries is definitely a good first step; you never know, perhaps the problem was already fixed.

Otherwise, we need to find a way to reproduce the problem. If you're sending log files in somehow, perhaps it's possible to see a pattern when this is happening.

Furthermore: how frequently does this occur? Relative to the total number of sessions, I mean?

**Comment by kheftel** [comment]
Subscribing to this thread to see how it turns out - quadtreesprite looks very interesting and I'm curious to see if it's the cause of the error before using.

**Comment by PrimaryFeather** [comment]
One more question: are you using Masks or any other of the new 1.7 features?

**Comment by LvLynx** [comment]
Sorry for the delay (long release cycle). We launched new version with all the newest libraries and error still happens.

We are not using any of 1.7 features yet. 
We log every in game action, or error. And now stats from last 4 days are 52 RangeErrors out of 58666 events. Its doesn't happen very often, but it shouldn't happen at all.

We haven't been able to reproduce it locally. We know for sure its not tied to flash version. We see quite big range of different flash versions in logs. Its not tied to game run time or free memory.

Probably something that happens in-game triggers it, we just haven't been able to find it.

We could try to add some debug code to Starling to find out what it causing it, we just don't have ideas where to start.

Thank you

**Comment by PrimaryFeather** [comment]
> Its doesn't happen very often, but it shouldn't happen at all.

Agreed, of course. At least it's good to know that it's not very common, although that will make it harder to track down.

It would be great if you could add some debug code, yes! That would help for sure. I recommend you modify "DisplayObjectContainer.render" by adding the following code:

```as3
for (var i:int=0; i<numChildren; ++i)
{
    // var child:DisplayObject = mChildren[i]; <== old code. Replaced by:

    var child:DisplayObject;

    if (i in mChildren) child = mChildren[i];
    else
    {
        trace("RangeError in 'render' of " + getQualifiedClassName(this));
        trace("Parent type: " + getQualifiedClassName(parent));
        trace("requested " + i + " of " + mChildren.length);
        trace("expected length: " + numChildren);
        break;
    }

    // ... here, normal code goes on.
    if (child.hasVisibleArea)
```

That gives us some information about the context of the error. Perhaps that brings us one step forward!
Thanks a lot in advance!

**Comment by accessible89** [comment]
Hi. I have same problem when use Starling 1.7 and Feathers last ver. When I use Scroll Container from Feathers, this error happens.

**Comment by jamikado** [comment]
You have to use Feathers 2.2.0beta+ with Starling 1.7:
http://forum.starling-framework.org/topic/total-failure-with-17

**Comment by PrimaryFeather** [comment]
[As a side-note, the original problem from LvLynx has nothing to do with Feathers. We'd see that in the stack trace, and it would happen much more frequently.]

**Comment by LvLynx** [comment]
Sorry again for long delay. We were in final feature freeze before launch. We just launched, so we have more data from larger user pool.

[STARLING #1125 ERROR]
RangeError in 'render' of map::Area
Parent type: map::World 
requested 9 of 9 
expected length: 11

[STARLING #1125 ERROR]
RangeError in 'render' of map::Area
Parent type: map::World 
requested 12 of 12 
expected length: 13 

Errors are only from map::Area with lot different variations in requested and expected length.
I made DisplayObjectContainer mChildren protected and overrode render() in Area to trace children changes, I also attached image to  this post to better explain whats happening.

![sd](https://cloud.githubusercontent.com/assets/9196835/9420292/80c3751e-486c-11e5-8810-75694349a965.png)

So what happens here is: Area is main container for game objects. In default state we have 8 children: [object Camera],[object GroundMap],[object Tilemap],[object Objmap],[object CloudLayer],[object Sprite],[object Brush],[object Editor]

When user is doing actions ingame new childs are added and removed, for example [object MapDropIcon] for every dropped resource reward (see screenshot - twigs on right side from character with helmet) after some time icon is removed with help from juggler. When player hovers over map object [object MapHPBar] is added and so on. At the moment of taking screenshot I had 12 children. (3 resource icons and MapHPBar).

I have once managed to forcefully encounter this error when character was doing lot of actions off screen and I was wildly panning map back and forth. But error logs show that this is still happening and probably in some other more easily encountered way.

Some race condition in render() and object removal maybe? MapDropIcon/onDestroy() calls removeFromParent(true);

**Comment by PrimaryFeather** [comment]
Thanks for getting back to me on this, and congratulations on your launch! The screenshot looks amazing, great work! =)

Okay, your problem analysis is helpful. Indeed, it does seem as if a child is being removed while the render method loops over the children — just as we expected. 

Now, I think the next step would be to find out which type of object is being removed when the error occurs. With this information, you can then look at all places where this type of object may be removed (manually, or if that does not help, with an "Event.REMOVED" event listener and additional logic).

I'd do that like this: make another change to the render method:

```as3
private var mLastChildren:Vector.<DisplayObject> = new <DisplayObject>[];

public override function render(support:RenderSupport, parentAlpha:Number):void
{
    var alpha:Number = parentAlpha * this.alpha;
    var numChildren:int = mChildren.length;
    var blendMode:String = support.blendMode;
    
    // create copy of the 'mChildren' vector
    for (i=0; i<numChildren; ++i) mLastChildren[i] = mChildren[i]
    mLastChildren.length = numChildren;
    
    for (var i:int=0; i<numChildren; ++i)
    {
        var child:DisplayObject = mChildren[i];

        if (i in mChildren) child = mChildren[i];
        else
        {
            trace("RangeError in 'render' of " + getQualifiedClassName(this));
            trace("Parent type: " + getQualifiedClassName(parent));
            trace("requested " + i + " of " + mChildren.length);
            trace("expected length: " + numChildren);
            
            // now log out which type of child has been removed
            for (var j:int=0; j<mLastChildren.length; j++)
            {
                var prevChild:DisplayObject = mLastChildren[i];
                if (mChildren.indexOf(prevChild) == -1)
                {
                    trace("removed child: " + getQualifiedClassName(prevChild));
                }
            }
            
            break;
        }
        
        if (child.hasVisibleArea)
        {
            // ... here, normal code goes on.
        }
    }
}
```

I know it's painful to do this in such small steps, but I'm optimistic that this information will lead us to the root of the problem. :+1:

**Comment by PrimaryFeather** [comment]
Lacking any additional data, I will close this issue. I hope you found a solution!
Otherwise, feel free to open the issue again so we can work on a fix.
