### ISSUE TITLE
Button 'onTouch' event null reference

### ISSUE THREAD

**Issue by cgascons** [Gamua/Starling-Framework#747]
Hi there Daniel,

I'm facing a pretty random issue regarding the touch management on the Button.as class. My app in production is logging null reference errors at the 'onTouch' class. I only managed to generate this issue once, "spamming" a button and moving it at the same time. It crashed me at the line 166 of this class. The mTriggerBounds variable was null, which makes me think that somehow, it "skipped" or didn't get into the previous BEGAN/DOWN condition where this variable gets filled. I spent quite a while yesterday trying to get a 100% repro steps, but wasn't lucky at all. I guess a security check could easily solve the issue, but to be honest I'm intrigued on what could be happening here!

Thanks for the support!

**Comment by PrimaryFeather** [comment]
Wow, that's really tricky. I just looked at the code again, and — just as you — I can't (yet) see how this state could emerge.

I suppose you don't do anything special with the button, right? Like changing the "state" manually, or adding additional touch event handlers?

**Comment by cgascons** [comment]
That's what I call a really quick response :)

Unfortunately I don't change the state manually, the only additional event listener I have implemented is an extra 'onTouch' event (listening only to the HOVER event) on my project buttons that I use in order to show/hide a Tooltip label. But not all the buttons have tooltips so I guess it's pretty random.

**Comment by PrimaryFeather** [comment]
Hm ... I'll play around with it myself and will get back to you with the results!

**Comment by cgascons** [comment]
Thanks Daniel!

**Comment by PrimaryFeather** [comment]
To be honest, I couldn't reproduce the original problem, and I still can't imagine how it's happening. :wink:

However, I found another case where the same exception could arise. Add the following touch event handler to a button:

```as3
setTimeout(function():void
{
    button.state = ButtonState.DOWN;
}, 1000);
```

Now move the cursor over the button *before* the timeout ends; when the button has changed its state, keep the cursor stationary, but press the mouse button. Now, with the button still down, move the cursor. 

This will lead to a null reference exception in the old version.
To avoid this, I'm now simply creating an empty "mTriggerBounds" rectangle in the constructor. This shouldn't hurt anyone — and such exceptions are avoided.

... it bothers me that we didn't get to the root of the original problem. But one way or the other: the problem won't pup up any longer. :smile:

**Comment by cgascons** [comment]
Indeed it sounds like a good fix! The steps to crash you said are quite similar to the ones I used to reproduce the issue the first time, so couldn't it be that by spamming and moving the mouse repeatedly created a weird mess on the buttons states and therefore, jumped to a state where the mTriggerBounds wasn't yet created? Anyways, I'm sure like you said that the issue will not be bothering us again anymore so thanks as always for such a quick fix!

**Comment by PrimaryFeather** [comment]
> couldn't it be that by spamming and moving the mouse repeatedly created a weird mess on the buttons states and therefore, jumped to a state where the mTriggerBounds wasn't yet created?

Yes, it must be something like that, though I couldn't find the exact order of events that would cause that trouble. But there must be something I'm overlooking — I remember a similar bug a while ago, which looked equally impossible to me, until someone pointed out how it could happen. :wink:
